### ISSUE TITLE
Wikipedia

### ISSUE THREAD

**Issue by Pluto1010** [mre/awesome-static-analysis#11]
Hello!

I think you know this but there are list at wikipedia containing static analysis tools.

https://de.wikipedia.org/wiki/Liste_von_Werkzeugen_zur_statischen_Codeanalyse
https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis

**Comment by mre** [comment]
Oh thanks for the links! I did not know that. :smiley: 
I looked through the lists and saw that a lot of them are deprecated or abandoned.
Other are already mentioned here. But there is a longer list of interesting tools that are still missing.
My plan is to add the missing tools as soon as possible.

**Comment by Pluto1010** [comment]
No problem! Good to hear. Bye
