### ISSUE TITLE
Add cqc (Code Quality Checker)

### ISSUE THREAD

**Issue by xcatliu** [mre/awesome-static-analysis#114]
Hi, I've written a tool to check the code quality of JavaScript, here is the link: https://github.com/xcatliu/cqc
Could you please help review if this can be added to the awesome list?
Thanks!

**Comment by mre** [comment]
Hi @xcatliu,
took a look at your tool and I would definitely add it to the list.
Could you create a pull request for that? 😃 
Cheers,
Matthias
