### ISSUE TITLE
Activity check

### ISSUE THREAD

**Issue by impredicative** [mre/awesome-static-analysis#129]
@mre Hi. I haven't seen much activity from you lately toward this project. Is everything okay? As you see, there have been outstanding PRs, etc. Thanks.

**Comment by mre** [comment]
Heyo @impredicative,
thanks for the ping. I'm doing fine. Was a bit busy recently, but I hope we'll catch up soon.
Actually I was working on a [CI tool to ease our work](https://github.com/mre/awesome-static-analysis-ci). It's basically a linter for linters. 😆 
I hope to integrate it very soon.

**Comment by mre** [comment]
Merged the outstanding pull requests. We're back on track. 😁

**Comment by mre** [comment]
Oh, and I wrote an article about that. 😉 
https://matthias-endler.de/2017/obsolete/
