### ISSUE TITLE
Containers: Recommended adds

### ISSUE THREAD

**Issue by gjyoung1974** [mre/awesome-static-analysis#146]
@mre  WRT Containers, how about: 
+
1. https://layeredinsight.com
2. https://anchore.io/

Thanks!
~G

**Comment by mre** [comment]
Hey @gjyoung1974. Nice findings!  
I would add those to the list if you want to send me a pull request. Sounds good?  
If so, please add them to the [webservice section](https://github.com/mre/awesome-static-analysis#web-services).
If you need help with that, no worries I got you covered.

**Comment by mre** [comment]
Oh yeah, here are a [few guidelines](https://github.com/mre/awesome-static-analysis/blob/master/CONTRIBUTING.md).
