### ISSUE TITLE
JS Dependencies Scanner

### ISSUE THREAD

**Issue by rojaster** [mre/awesome-static-analysis#150]
I found this tool : https://github.com/RetireJS/retire.js , though, I am kinda hesitating about adding the tool to the list, because it's not a pure static code analysis. What do you think?

**Comment by Hipapheralkus** [comment]
since there is a DependencyCheck reference in Java, which basically serves the same purpose, I guess it's ok to add it:)

**Comment by mre** [comment]
Yes, I share @Hipapheralkus' opinion: I think it makes for a good addition. Would be happy to accept a PR.

**Comment by mre** [comment]
Had a few more minutes so I added it to the list. Thanks for your suggestion. 🏖
