### ISSUE TITLE
tis-interpreter and sanitizers

### ISSUE THREAD

**Issue by arthaud** [mre/awesome-static-analysis#164]
Hello,

tis-interpreter is not a static analyzer, it basically does runtime analysis.

Should we remove it?
Should we create an "awesome-dynamic-analysis" repo?

If you want to keep it, then there are plenty of other runtime analysis tools (ASAN/UBSan/etc) that should be listed here too.

**Comment by mre** [comment]
Hi @arthaud,

after giving this some thought I guess you're right. Moved it to https://github.com/mre/awesome-dynamic-analysis and gave you admin permission.
If you can you like, you could also add the other tools you mentioned.

Thanks for the suggestion! 😃
