### ISSUE TITLE
LibVCS4j

### ISSUE THREAD

**Issue by msteinbeck** [mre/awesome-static-analysis#166]
I propose to add https://github.com/uni-bremen-agst/libvcs4j. The library allows existing analysis tools to examine the evolution of software systems by providing a common API for different version control systems and issue trackers. Furthermore, there is a subproject that is capable of collecting different size and complexity related metrics for several programming languages (using the ConQAT scanner library).

**Comment by mre** [comment]
Sounds good! I'm just not sure about the category, though.
How about "Linting Engines" or simply "Helper Tools"? What do you think?

**Comment by msteinbeck** [comment]
How about "Supporting Tools"?

**Comment by mre** [comment]
Sounds good! Can you create the pull request?
