### ISSUE TITLE
TSanCode should be TScanCode

### ISSUE THREAD

**Issue by kokke** [mre/awesome-static-analysis#174]
Hi and thanks for an awesome list.

I have recently discovered [TscanCode from Tencent](https://github.com/Tencent/TscanCode) and noticed that the spelling on this list has a typo: it says TsanCode instead of TscanCode.

I don't feel that such a one-character edit merits a PR ?

FWIW TscanCode seems to be built on [cppcheck](https://github.com/danmar/cppcheck), but it finds issues that cppcheck doesn't, given the same code base. It is somewhat slower than cppcheck, but works in a similar manner (on token streams).

Have a nice day

**Comment by mre** [comment]
As I side note, I always had the suspicion that something was wrong with the spelling, but I couldn't point my finger at it. 😆
