### ISSUE TITLE
Does my library, violations-lib, belong here?

### ISSUE THREAD

**Issue by tomasbjerre** [mre/awesome-static-analysis#212]
I develop this library: https://github.com/tomasbjerre/violations-lib

I would happily have it added, if you feel it belongs here?

**Comment by mre** [comment]
Hey @tomasbjerre,
this library absolutely belongs here!
I didn't even know that something like this existed, very useful.

May I suggest the Supporting Tools category? (https://github.com/mre/awesome-static-analysis#supporting-tools).
Looking forward to your PR.
