### ISSUE TITLE
User reviews for these static analysis tools to complement this list

### ISSUE THREAD

**Issue by danielleitcs** [mre/awesome-static-analysis#217]
Thanks for this comprehensive list. You might also find user reviews for many of these solutions on IT Central Station to be helpful here. 

As an example, users in our community looking for static analysis tools often read reviews for tools such as Veracode and Appscan. You can see a direct comparison between these two solutions [here](https://www.itcentralstation.com/products/comparisons/ibm-security-appscan_vs_veracode/tzd/c574-sbc-213).

*Disclaimer: I work at IT Central Station.

**Comment by mre** [comment]
Thanks for the hint @danielleitcs. I'll keep that bookmarked in case I want to compare tools in the future.
