### ISSUE TITLE
Top-Link at website links to https://awesome-static-analysis.com/

### ISSUE THREAD

**Issue by andygrunwald** [mre/awesome-static-analysis#227]
The link at the hat (top left corner) at https://matthias-endler.de/awesome-static-analysis/ links to a non-existing website https://awesome-static-analysis.com/

<img width="1304" alt="screen shot 2019-02-05 at 15 59 57" src="https://user-images.githubusercontent.com/320064/52281838-3b989c80-295f-11e9-818a-e982c390f76c.png">

**Comment by mre** [comment]
Thanks! Fixed. 🌞
