### ISSUE TITLE
lintr isn't proprietary

### ISSUE THREAD

**Issue by russHyde** [mre/awesome-static-analysis#234]
Hi. The `lintr` package for R isn't a propriatary tool; but your list suggests that it is. It was released on an MIT license. see [here](https://github.com/jimhester/lintr)

**Comment by Harvester57** [comment]
It is copyrighted : https://github.com/jimhester/lintr/blob/master/LICENSE

**Comment by mre** [comment]
There was a discussion about this over at https://github.com/jimhester/lintr/issues/320. It is indeed `MIT` licensed. Will fix that. Thanks for the hint @russHyde.

**Comment by russHyde** [comment]
No problem. There are a couple of other static analysis tools for R (styler, goodpractice). I can add them via a pr if you like

**Comment by mre** [comment]
That would be amazing, thanks. +💯

**Comment by mre** [comment]
Fixed by #235
