### ISSUE TITLE
Request to support Delphi/Pascal language

### ISSUE THREAD

**Issue by darianmiller** [mre/awesome-static-analysis#254]
Pascal (either Delphi or FreePascal)

**Comment by mre** [comment]
If anyone knows tools, go ahead and create a PR. 😊

**Comment by nvhaver** [comment]
How about https://www.peganza.com/?

I haven't used it before, but perhaps @darianmiller can check it out?
(found out about it through SO: https://stackoverflow.com/questions/532986/are-there-any-static-code-analysis-tools-for-delphi-pascal)

**Comment by mre** [comment]
While I didn't execute it, it does indeed look awesome. The documentation is up-to-date and there was a recent release. I'd welcome a pull request to add it @nvhaver.

**Comment by darianmiller** [comment]
I own Peganza, it's an awesome static analysis tool for Delphi.  Another choice is FixInsight: https://www.tmssoftware.com/site/fixinsight.asp

**Comment by mre** [comment]
Ah, that's great. If you like, you could add both tools to the list by creating a pull request. 
Probably inside a new "Delphi" section. :)

**Comment by darianmiller** [comment]
Well I tried to do a PR, but it's failing.  I assumed it was too long of length (200 characters suggested) but it's under that limit and still fails.  Not sure how to correct: 

"Error: Some(ErrorMessage { msg: "Tool does not match regex: * [Fix Insight]( https://www.tmssoftware.com/site/fixinsight.asp) :copyright: - A free IDE Plugin for static code analysis. A *Pro* edition includes a command line tool for automation purposes." })"

**Comment by mre** [comment]
Yeah that's because the CI pipeline is a bit weird. It didn't like the space in front of the parenthesis.
I'll have to prioritize #194 to get away from those formatting issues at some point.
Anyway thanks for adding those three tools. Much appreciated.
