### ISSUE TITLE
should CppDepend be removed?

### ISSUE THREAD

**Issue by andy5995** [mre/awesome-static-analysis#272]
I clicked through to CppDepend and tried to download the 14-day trial version, which required me to first enter my email. After I did, and clicked the download link, I got this email

>Hello,

>Thanks for your interest in achieving higher code quality with CppDepend.

>Our technical team will contact you shortly with your download link for CppDepend on Linux.

>Best regards and have a nice day.

>The CppDepend team

That was on Jun 24th. I never heard back until today, July 15th, when I got this email, with no "unsubscribe" link:

>Hello,

>We are happy to announce that CppDepend v2019.2 for Linux has been released and is now available for download!

>You can download CppDepend v2019.2 here:
https://www.cppdepend.com/Thank-You-For-Downloading-CppDepend?os=L64

>To install CppDepend, just unzip the files in a private application folder on your machine.

>Check out the online documentation to quickly learn how to begin analyzing your first project: https://www.cppdepend.com/GettingStartedForLinux

>Watch more videos to get started with each feature here: https://www.cppdepend.com/videos

>Your feedback is welcome at support@codergears.com

>Happy Hunting!

>The CoderGears Team.

**Comment by Harvester57** [comment]
But what would be the rationale to remove it from the list ?

**Comment by nvhaver** [comment]
I briefly checked out the tool, or at least its installation. Once you download and unpack the archive (tar.gz format) (using the link posted by @andy5995), running the tool allows you to start the 14 day evaluation period. That being said... the GUI does not render correctly at all. It's so bad that I'm not able to use the tool correctly (seems to be some hdpi scaling issues or just bad GUI design).

It also seems that the visual studio add-ons are not available as a trial.

I might check out the console version later on, but for now I have to conclude that the GUI version of the tool is not usable. So far not that awesome...

**Comment by mre** [comment]
I agree that this is a sup-par user-experience and it might mislead people into downloading and testing the tool only to find out that it's not matching our standards. Hence, i suggest to add a `:warning:` sign to it for the time being.

**Comment by mre** [comment]
Okay i think that will do for now. If we want to remove it completely, we can discuss that at a later point in time. Thanks for raising this topic @andy5995.
