### ISSUE TITLE
Adding IDEs as a section

### ISSUE THREAD

**Issue by Mkohm** [mre/awesome-static-analysis#299]
Would adding IDEs as a separate section be useful? For example IDEs like Jetbrains IDEA and Android Studio comes bundled with tools like idea-inspector and android lint. They also provide a lot of tools functionality for refactoring, extracting, reordering of methods, auto-formatting - using static analysis.  Can create a PR for it if you think it is a good idea.

**Comment by mre** [comment]
I don't know.
A list is quite limited in that regard. What we'd need is a multi-dimensional to represent entries, e.g. each tool gets a list of tags and one of them would be `ide`. See the discussion at https://github.com/mre/awesome-static-analysis/issues/194.
I'd say, let's create an IDE section for now and we can take care of a better structure later. So, please go ahead and propose a PR if you like. 👍

**Comment by mre** [comment]
@Mkohm, any update on this?

**Comment by Mkohm** [comment]
@mre just created it:) https://github.com/mre/awesome-static-analysis/pull/334

Totally forgot to do it.

**Comment by mre** [comment]
Merged. Thanks!
