### ISSUE TITLE
CSS-Category?

### ISSUE THREAD

**Issue by andygrunwald** [mre/awesome-static-analysis#33]
I stumbled upon https://github.com/brigade/scss-lint and wondered if CSS will be useful as a new category here?
I would vote for yes, because

* HTML is there as well
* @creinartz can add tons of tools there

Whats your opinion?

**Comment by mre** [comment]
I'd say: go for it.
And thanks for discussing this before. :smiley:

**Comment by andygrunwald** [comment]
See #36

**Comment by creinartz** [comment]
Two back-end people taking care for adding a CSS section. <3 That's so adorably! 
I'll add tons of tools
