### ISSUE TITLE
Adding detekt-hint as an awesome tool (https://github.com/Mkohm/detekt-hint)

### ISSUE THREAD

**Issue by Mkohm** [mre/awesome-static-analysis#335]
Hi again @mre :) 

I am currently developing a new tool for detection of design principle violations in Kotlin. https://github.com/Mkohm/detekt-hint

It is not _awesome_ just yet, but i would like to know what are the requirements for being so? Does it need a certain amount users?

If it could be included in this list, it would most likely get more traffic and be awesome faster 😬  But i am aware that you probably don't want unfinished products in the list.

**Comment by mre** [comment]
Hey @Mkohm,

nice to hear that you're working on a new tool. Looks great from what I can tell.
The rules for addition are quite simple:

Each tool on the list should be

   * actively maintained (more than one contributor)
   * actively used (have more than 20 stars on Github or similar impact)
   * relatively mature (project exists for at least three months)

See the [contributing guidelines here](https://github.com/mre/awesome-static-analysis/blob/master/CONTRIBUTING.md).
So it looks like you're not far away from achieving that. 😉 Looking forward to receiving your PR in the near future. ⭐️

**Comment by Mkohm** [comment]
Sounds good 👌Closing the issue then. Will create a PR when the time is right!
