### ISSUE TITLE
CodePeer wrongly listed as proprietary software

### ISSUE THREAD

**Issue by yannickmoy** [mre/awesome-static-analysis#65]
Hi, 

As one of the developers of CodePeer at AdaCore, I'd like to point out that it is in fact distributed to our customers with GPLv3 license (AdaCore is a FLOSS tool provider), but that there is no "free" (as in free beer) version available on the Web.

It is also not the only available static anlyzer for Ada, you could list also:
- PolySpace Ada (https://www.mathworks.com/products/polyspace-ada.html) 
- Understand for Ada (https://scitools.com/ada-programming-essential/)
- Axivion Bauhaus Suite (https://www.axivion.com/en/products-services-9#products_bauhaussuite)

**Comment by mre** [comment]
Good to know @yannickmoy. I've changed the license to OSS and added the tools you mentioned. Thanks! 👍
