### ISSUE TITLE
PMD is not a Java-only tool

### ISSUE THREAD

**Issue by jsotuyod** [mre/awesome-static-analysis#68]
Currently PMD is listed under Java, but in truth it's a multi-language tool.

It currently supports:
- Salesforce.com's APEX
- Java
 - JavaScript
 - PLSQL
 - Apache Velocity
 - XML
 - XSL

The next version (5.6.0) will also include support for Salesforce.com's Visualforce.

Also, the CPD tool, which is part of PMD, and searches for duplicate code works on:

- Java
- C
- C++
- C#
- Groovy
- PHP
- Ruby
- Fortran
- JavaScript
- PLSQL
- Apache Velocity
- Scala
- Objective C
- Matlab
- Python
- Go
- Swift
- Salesforce.com Apex

Once again, the next version (5.6.0) will also include support for Salesforce.com's Visualforce.

There is even [a big project for this year](https://github.com/pmd/pmd/wiki/Project-Ideas-%5BMature%5D#full-antlr-support) that will move several of these CPD-only supported languages to fully-supported.

Thanks in advanced!

**Comment by mre** [comment]
Thanks for the hint! I've moved PMD to the "multiple languages" section.
Don't hesitate to create a pull request next time. Would happily merge it. 🌻
