### ISSUE TITLE
Use the official "awesome" logo

### ISSUE THREAD

**Issue by saschagrunert** [mre/awesome-static-analysis#80]
I would suggest to use their official logo here to make it easier recognizable. 

![](https://camo.githubusercontent.com/1131548cf666e1150ebd2a52f44776d539f06324/68747470733a2f2f63646e2e7261776769742e636f6d2f73696e647265736f726875732f617765736f6d652f6d61737465722f6d656469612f6c6f676f2e737667)

**Comment by mre** [comment]
Thanks for your suggestion. I kinda prefer the current logo, though. 😉

**Comment by saschagrunert** [comment]
Alright. :)
