### ISSUE TITLE
You may want to add lizard

### ISSUE THREAD

**Issue by agirorn** [mre/awesome-static-analysis#86]
You may want to add lizard for C/C++ (works with C++14), Java, C# (C Sharp), JavaScript, Objective C, Swift, Python, Ruby, TTCN-3, PHP, Scala and GDScript languages
 
https://github.com/terryyin/lizard

**Comment by mre** [comment]
Sounds nice! Can you create a pull request for that? I would merge it right away 😃

**Comment by markhermelinggt** [comment]
Matthias,

The addition I was trying to make was for CodeSonar from GrammaTech, but I am unable to publish my branch and can not create a push request either.

The addition I was trying to make was:

* [CodeSonar from GrammaTech](https://www.grammatech.com/products/codesonar) :copyright: - Advanced, whole program, deep path, static analysis of C and C++ with user-friendly explanations and code and path visualization.


I have no clue why GitHub is not allowing me to do this. The only thing I can think off is that this is a commercial account, maybe I need to make a personal login?

Thanks!
Mark


—
Mark Hermeling | GrammaTech | Senior Director Product Marketing
mobile +1 (607) 351-5719 | www.grammatech.com

**Comment by mre** [comment]
I see. That's strange. Checked your profile and did not see a fork of my project there. You need a fork to create a PR. [Here's an in-depth description](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).
Another way is to simply edit the `README.md` file directly.
For that, click on the `README.md` file in the project and click on the little `Edit` pen on the top right corner. This will automatically create a fork of the project and guide you through the process.

**Comment by mre** [comment]
Click here to go the [README.md](https://github.com/mre/awesome-static-analysis/blob/master/README.md) and then find the edit pen here:
![grafik](https://user-images.githubusercontent.com/175809/26930340-5d693116-4c5d-11e7-983d-d978e86ad19c.png)
Pretty handy 😃

**Comment by markhermelinggt** [comment]
Thanks Matthias,

That was easy :)

Regards,
Mark

—
Mark Hermeling | GrammaTech | Senior Director Product Marketing
mobile +1 (607) 351-5719 | www.grammatech.com

**Comment by mre** [comment]
You're welcome. Merged with #88. Closing.
