### ISSUE TITLE
NodeJS security scanner

### ISSUE THREAD

**Issue by javixeneize** [mre/awesome-static-analysis#96]
Hi Matthias

I am after a tool to do static analysis on nodeJS. Have you heard about any tool? The closest i have found is a javascript plugin for SonarQube, but it only contains 9 security rules :/

Thanks

**Comment by mre** [comment]
Hi @javixeneize,
have you searched the list for node? There's some interesting tools in there.
Namely, [Aether](http://aetherjs.com/) is a standalone tool, that you could try.
If you don't mind using a service, you can also check out [bithound](https://www.bithound.io/), [Node Security Platform](https://nodesecurity.io/) and [snyk](https://snyk.io/). The last two are specifically focused on security.
Hope that helps. If you come across a helpful tool that's not on the list, don't hesitate to create a Pull Request 😉
